const UI_THEMES = {
        sunny: {
          id: 'sunny',
          name: 'Sunny Beach',
          icon: '☀️',
          gradient: 'from-amber-400 to-orange-500',
          bodyBg: 'bg-amber-50 text-slate-800',
          headerBg: 'bg-white/95 border-amber-200 text-slate-900 shadow-xs',
          cardBg: 'bg-white/95 border-amber-200 shadow-md text-slate-800',
          dialogueBg: 'bg-amber-100/90 border-amber-300 text-amber-950',
          shelfBg: 'bg-slate-50/90 border-slate-200',
          rackBg: 'bg-amber-900/10 border-amber-200/80',
          itemCard: 'bg-white hover:bg-amber-50 border-amber-200 hover:border-amber-400 text-slate-800',
          basketBg: 'bg-amber-50/60 border-amber-200/80',
          keypadBg: 'bg-amber-100/80 border-amber-200',
          keypadKey: 'bg-white hover:bg-amber-50 text-slate-800 border-amber-200',
          btnPrimary: 'bg-amber-500 hover:bg-amber-600 text-white shadow-amber-200',
          btnSecondary: 'bg-amber-200 hover:bg-amber-300 text-amber-950 border-amber-300',
          badgeBg: 'bg-amber-200 text-amber-900',
          navActive: 'bg-amber-500 text-white shadow-xs',
          navInactive: 'bg-white text-slate-700 hover:bg-slate-100 border border-slate-200',
          stepActive: 'bg-amber-500 text-white shadow-xs font-bold border-amber-600',
          stepDone: 'bg-emerald-500 text-white font-bold border-emerald-600',
          stepNext: 'bg-slate-100 text-slate-500 border-slate-300',
          textTitle: 'text-amber-950',
          textSub: 'text-amber-800',
          isDark: false
        },
        sunset: {
          id: 'sunset',
          name: 'Atoll Sunset',
          icon: '🌅',
          gradient: 'from-rose-500 to-purple-600',
          bodyBg: 'bg-gradient-to-br from-slate-950 via-rose-950 to-purple-950 text-rose-100',
          headerBg: 'bg-slate-900/90 border-rose-800/80 text-rose-100 shadow-rose-950/30',
          cardBg: 'bg-slate-900/95 border-rose-800/80 shadow-rose-950/50 text-rose-100',
          dialogueBg: 'bg-rose-950/80 border-rose-700/80 text-rose-100',
          shelfBg: 'bg-slate-950/60 border-rose-800/60',
          rackBg: 'bg-rose-950/40 border-rose-800/60',
          itemCard: 'bg-slate-800/90 hover:bg-rose-900/40 border-rose-700/60 hover:border-rose-400 text-rose-100',
          basketBg: 'bg-slate-950/80 border-rose-800/60',
          keypadBg: 'bg-rose-950/60 border-rose-800/60',
          keypadKey: 'bg-slate-800 hover:bg-rose-900/60 text-rose-100 border-rose-700/50',
          btnPrimary: 'bg-gradient-to-r from-rose-500 to-amber-500 hover:from-rose-600 hover:to-amber-600 text-white shadow-rose-900/50',
          btnSecondary: 'bg-rose-900/60 hover:bg-rose-800/80 text-rose-200 border-rose-700/60',
          badgeBg: 'bg-rose-900/80 text-rose-200 border border-rose-700/60',
          navActive: 'bg-rose-600 text-white shadow-xs',
          navInactive: 'bg-slate-800/80 text-rose-200 hover:bg-rose-900/50 border border-rose-800',
          stepActive: 'bg-rose-600 text-white shadow-xs border-rose-500',
          stepDone: 'bg-emerald-600 text-white border-emerald-500',
          stepNext: 'bg-slate-800 text-rose-300/50 border-rose-900',
          textTitle: 'text-rose-100',
          textSub: 'text-rose-300',
          isDark: true
        },
        lagoon: {
          id: 'lagoon',
          name: 'Lagoon Blue',
          icon: '🌊',
          gradient: 'from-cyan-500 to-teal-600',
          bodyBg: 'bg-gradient-to-br from-cyan-950 via-slate-900 to-teal-950 text-cyan-100',
          headerBg: 'bg-slate-900/90 border-cyan-800/80 text-cyan-100 shadow-cyan-950/30',
          cardBg: 'bg-slate-900/95 border-cyan-800/80 shadow-cyan-950/50 text-cyan-100',
          dialogueBg: 'bg-cyan-950/80 border-cyan-700/80 text-cyan-100',
          shelfBg: 'bg-slate-950/60 border-cyan-800/60',
          rackBg: 'bg-cyan-950/40 border-cyan-800/60',
          itemCard: 'bg-slate-800/90 hover:bg-cyan-900/40 border-cyan-700/60 hover:border-cyan-400 text-cyan-100',
          basketBg: 'bg-slate-950/80 border-cyan-800/60',
          keypadBg: 'bg-cyan-950/60 border-cyan-800/60',
          keypadKey: 'bg-slate-800 hover:bg-cyan-900/60 text-cyan-100 border-cyan-700/50',
          btnPrimary: 'bg-gradient-to-r from-cyan-500 to-teal-500 hover:from-cyan-600 hover:to-teal-600 text-white shadow-cyan-900/50',
          btnSecondary: 'bg-cyan-900/60 hover:bg-cyan-800/80 text-cyan-200 border-cyan-700/60',
          badgeBg: 'bg-cyan-900/80 text-cyan-200 border border-cyan-700/60',
          navActive: 'bg-cyan-600 text-white shadow-xs',
          navInactive: 'bg-slate-800/80 text-cyan-200 hover:bg-cyan-900/50 border border-cyan-800',
          stepActive: 'bg-cyan-600 text-white shadow-xs border-cyan-500',
          stepDone: 'bg-emerald-600 text-white border-emerald-500',
          stepNext: 'bg-slate-800 text-cyan-300/50 border-cyan-900',
          textTitle: 'text-cyan-100',
          textSub: 'text-cyan-300',
          isDark: true
        },
        night: {
          id: 'night',
          name: 'Night Market',
          icon: '🌙',
          gradient: 'from-indigo-600 to-purple-800',
          bodyBg: 'bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 text-indigo-100',
          headerBg: 'bg-slate-900/90 border-indigo-800/80 text-indigo-100 shadow-indigo-950/30',
          cardBg: 'bg-slate-900/95 border-indigo-800/80 shadow-indigo-950/50 text-indigo-100',
          dialogueBg: 'bg-indigo-950/80 border-indigo-700/80 text-indigo-100',
          shelfBg: 'bg-slate-950/60 border-indigo-800/60',
          rackBg: 'bg-indigo-950/50 border-indigo-800/60',
          itemCard: 'bg-slate-800/90 hover:bg-indigo-900/40 border-indigo-700/60 hover:border-indigo-400 text-indigo-100',
          basketBg: 'bg-slate-950/80 border-indigo-800/60',
          keypadBg: 'bg-indigo-950/60 border-indigo-800/60',
          keypadKey: 'bg-slate-800 hover:bg-indigo-900/60 text-indigo-100 border-indigo-700/50',
          btnPrimary: 'bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 text-white shadow-indigo-900/50',
          btnSecondary: 'bg-indigo-900/60 hover:bg-indigo-800/80 text-indigo-200 border-indigo-700/60',
          badgeBg: 'bg-indigo-900/80 text-indigo-200 border border-indigo-700/60',
          navActive: 'bg-indigo-600 text-white shadow-xs',
          navInactive: 'bg-slate-800/80 text-indigo-200 hover:bg-indigo-900/50 border border-indigo-800',
          stepActive: 'bg-indigo-600 text-white shadow-xs border-indigo-500',
          stepDone: 'bg-emerald-600 text-white border-emerald-500',
          stepNext: 'bg-slate-800 text-indigo-300/50 border-indigo-900',
          textTitle: 'text-indigo-100',
          textSub: 'text-indigo-300',
          isDark: true
        },
        jungle: {
          id: 'jungle',
          name: 'Lush Palms',
          icon: '🌿',
          gradient: 'from-emerald-500 to-teal-700',
          bodyBg: 'bg-gradient-to-br from-emerald-950 via-teal-950 to-slate-900 text-emerald-100',
          headerBg: 'bg-slate-900/90 border-emerald-800/80 text-emerald-100 shadow-emerald-950/30',
          cardBg: 'bg-slate-900/95 border-emerald-800/80 shadow-emerald-950/50 text-emerald-100',
          dialogueBg: 'bg-emerald-950/80 border-emerald-700/80 text-emerald-100',
          shelfBg: 'bg-slate-950/60 border-emerald-800/60',
          rackBg: 'bg-emerald-950/40 border-emerald-800/60',
          itemCard: 'bg-slate-800/90 hover:bg-emerald-900/40 border-emerald-700/60 hover:border-emerald-400 text-emerald-100',
          basketBg: 'bg-slate-950/80 border-emerald-800/60',
          keypadBg: 'bg-emerald-950/60 border-emerald-800/60',
          keypadKey: 'bg-slate-800 hover:bg-emerald-900/60 text-emerald-100 border-emerald-700/50',
          btnPrimary: 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-600 hover:to-teal-600 text-white shadow-emerald-900/50',
          btnSecondary: 'bg-emerald-900/60 hover:bg-emerald-800/80 text-emerald-200 border-emerald-700/60',
          badgeBg: 'bg-emerald-900/80 text-emerald-200 border border-emerald-700/60',
          navActive: 'bg-emerald-600 text-white shadow-xs',
          navInactive: 'bg-slate-800/80 text-emerald-200 hover:bg-emerald-900/50 border border-emerald-800',
          stepActive: 'bg-emerald-600 text-white shadow-xs border-emerald-500',
          stepDone: 'bg-teal-600 text-white border-teal-500',
          stepNext: 'bg-slate-800 text-emerald-300/50 border-emerald-900',
          textTitle: 'text-emerald-100',
          textSub: 'text-emerald-300',
          isDark: true
        }
      };

const SHOPS = {
        fruit: {
          id: 'fruit',
          name: 'Island Produce Stall',
          subtitle: 'Fresh Maldivian fruits, coconuts & local produce',
          icon: 'fa-apple-whole',
          bgColor: 'bg-emerald-600',
          bannerBg: 'bg-gradient-to-r from-emerald-500 to-teal-600',
          products: [
            { id: 'kurumba', name: 'Kurumba (Coconut)', icon: '🥥', price: 15.00, unit: 'each' },
            { id: 'papaya', name: 'Papaya (Falho)', icon: '🥭', price: 25.00, unit: 'kg' },
            { id: 'mango', name: 'Local Mango (Anbu)', icon: '🥭', price: 10.00, unit: 'each' },
            { id: 'lime', name: 'Lime (Limbo)', icon: '🍋', price: 5.00, unit: 'pack' },
            { id: 'watermelon', name: 'Watermelon (Karakah)', icon: '🍉', price: 30.00, unit: 'each' },
            { id: 'curryleaves', name: 'Curry Leaves (Hikandhi)', icon: '🌿', price: 2.00, unit: 'bunch' },
          ]
        },
        bakery: {
          id: 'bakery',
          name: 'Island Bakery & Hedhikaa',
          subtitle: 'Warm ovens, fresh roshi & traditional short eats',
          icon: 'fa-bread-slice',
          bgColor: 'bg-amber-600',
          bannerBg: 'bg-gradient-to-r from-amber-500 to-orange-600',
          products: [
            { id: 'gulha', name: 'Fish Gulha (3pcs)', icon: '🧆', price: 10.00, unit: 'pack' },
            { id: 'masrooshi', name: 'Masrooshi', icon: '🫓', price: 12.00, unit: 'each' },
            { id: 'bajiya', name: 'Fish Bajiya', icon: '📐', price: 8.00, unit: 'each' },
            { id: 'roshi', name: 'Fresh Roshi (5pcs)', icon: '🥞', price: 15.00, unit: 'pack' },
            { id: 'bondibaiy', name: 'Saagu Bondibaiy', icon: '🥣', price: 20.00, unit: 'cup' },
            { id: 'cupcake', name: 'Coconut Cupcake', icon: '🧁', price: 15.00, unit: 'each' },
          ]
        },
        garden: {
          id: 'garden',
          name: 'Island Agriculture & Seeds',
          subtitle: 'Greenhouse plants, chili starts & soil beds',
          icon: 'fa-seedling',
          bgColor: 'bg-green-700',
          bannerBg: 'bg-gradient-to-r from-green-600 to-emerald-800',
          products: [
            { id: 'mirus', name: 'Githeyo Mirus Plant', icon: '🌶️', price: 25.00, unit: 'pot' },
            { id: 'papayaseed', name: 'Papaya Seeds', icon: '🌻', price: 10.00, unit: 'packet' },
            { id: 'can', name: 'Watering Can', icon: '🪴', price: 50.00, unit: 'each' },
            { id: 'pot', name: 'Clay Pot', icon: '🏺', price: 30.00, unit: 'each' },
            { id: 'fertilizer', name: 'Island Fertilizer', icon: '🧪', price: 40.00, unit: 'bag' },
            { id: 'sapling', name: 'Coconut Sapling', icon: '🌴', price: 60.00, unit: 'tree' },
          ]
        },
        toy: {
          id: 'toy',
          name: 'Island Crafts & Toys',
          subtitle: 'Handcrafted dhonis, shell puzzles & games',
          icon: 'fa-robot',
          bgColor: 'bg-rose-600',
          bannerBg: 'bg-gradient-to-r from-rose-500 to-pink-700',
          products: [
            { id: 'dhoni', name: 'Wooden Dhoni Craft', icon: '⛵', price: 80.00, unit: 'toy' },
            { id: 'blocks', name: 'Coconut Shell Blocks', icon: '🧱', price: 45.00, unit: 'set' },
            { id: 'puzzle', name: 'Coral Reef Puzzle', icon: '🧩', price: 35.00, unit: 'game' },
            { id: 'top', name: 'Spinning Top', icon: '🪀', price: 15.00, unit: 'each' },
            { id: 'bear', name: 'Plush Turtle Toy', icon: '🐢', price: 60.00, unit: 'toy' },
            { id: 'shellcraft', name: 'Cowrie Shell Craft', icon: '🐚', price: 25.00, unit: 'each' },
          ]
        },
        ocean: {
          id: 'ocean',
          name: 'Ocean & Fishery Supply',
          subtitle: 'Harbor fishing gear, roanu rope & ocean goods',
          icon: 'fa-anchor',
          bgColor: 'bg-cyan-700',
          bannerBg: 'bg-gradient-to-r from-cyan-600 to-blue-800',
          products: [
            { id: 'roanu', name: 'Coir Rope (Roanu)', icon: '🪢', price: 20.00, unit: 'bundle' },
            { id: 'tuna', name: 'Skipjack Tuna (Kalhubila)', icon: '🐟', price: 50.00, unit: 'fish' },
            { id: 'yellowfin', name: 'Yellowfin Chunk', icon: '🐠', price: 75.00, unit: 'kg' },
            { id: 'reel', name: 'Fishing Line Reel', icon: '🎣', price: 40.00, unit: 'tool' },
            { id: 'compass', name: 'Brass Compass', icon: '🧭', price: 120.00, unit: 'tool' },
            { id: 'hat', name: 'Fisherman Sun Hat', icon: '🧢', price: 35.00, unit: 'hat' },
          ]
        },
        space: {
          id: 'space',
          name: 'Space Depot & Tech',
          subtitle: 'Cosmic rations & tech gear for visiting research crews',
          icon: 'fa-rocket',
          bgColor: 'bg-indigo-700',
          bannerBg: 'bg-gradient-to-r from-indigo-600 to-violet-800',
          products: [
            { id: 'astrosnack', name: 'Astro Ration', icon: '🪐', price: 30.00, unit: 'pouch' },
            { id: 'oxygen', name: 'Oxygen Pod', icon: '🫧', price: 80.00, unit: 'cell' },
            { id: 'battery', name: 'Solar Cell Unit', icon: '🔋', price: 120.00, unit: 'unit' },
            { id: 'crystal', name: 'Energy Crystal', icon: '💎', price: 200.00, unit: 'gem' },
            { id: 'spacejuice', name: 'Astro Coconut Water', icon: '🧃', price: 25.00, unit: 'can' },
            { id: 'robotkit', name: 'Droid Sensor Parts', icon: '🤖', price: 150.00, unit: 'set' },
          ]
        }
      };

      const AVATARS = [
        { id: 'aminath', name: 'Aminath', avatar: '👩', title: 'Young Atoll Apprentice' },
        { id: 'moosa', name: 'Moosa', avatar: '👨‍🌾', title: 'Island Produce Expert' },
        { id: 'ibrahim', name: 'Captain Ibrahim', avatar: '👨‍✈️', title: 'Harbor Captain' },
        { id: 'mariyam', name: 'Mariyam', avatar: '👩‍🍳', title: 'Head Baker' },
        { id: 'hawwa', name: 'Hawwa', avatar: '👩‍🏫', title: 'Math Guide Teacher' },
        { id: 'hassan', name: 'Dr. Hassan', avatar: '🔬', title: 'Atoll Research Scientist' }
      ];

      const CUSTOMERS = [
        { name: "Aminath from Male'", avatar: '👩', story: 'Getting fresh produce and snacks for family tea!' },
        { name: 'Moosa the Farmer', avatar: '👨‍🌾', story: 'Preparing seeds and soil for island planting day.' },
        { name: 'Captain Ibrahim', avatar: '👨‍✈️', story: 'Stocking supplies for the fishing journey across the atoll.' },
        { name: 'Mariyam the Baker', avatar: '👩‍🍳', story: 'Sourcing ingredients for evening Dhivehi Hedhikaa.' },
        { name: 'Hawwa the Teacher', avatar: '👩‍🏫', story: 'Collecting classroom items for Key Stage math projects!' },
        { name: 'Dr. Hassan', avatar: '🔬', story: 'Calculating nutrition rates for island health research.' }
      ];

      const SHOP_UPGRADES = [
        { id: 'awning_red', type: 'awning', name: 'Traditional Striped Canopy', price: 100, icon: '⛺' },
        { id: 'awning_mint', type: 'awning', name: 'Tropical Mint Canopy', price: 150, icon: '🎪' },
        { id: 'sign_gold', type: 'sign', name: 'Sparkling Maldivian Sign', price: 200, icon: '🪧' },
        { id: 'mascot_parrot', type: 'mascot', name: 'Kavaiyya Mascot Parrot', price: 250, icon: '🦜' },
        { id: 'plant_flower', type: 'plant', name: 'Hibiscus Flower Boxes', price: 80, icon: '💐' },
        { id: 'lamp_festive', type: 'decor', name: 'Atoll Festival Lanterns', price: 120, icon: '🏮' }
      ];
export { UI_THEMES, SHOPS, AVATARS, CUSTOMERS, SHOP_UPGRADES };
